<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PeliculasSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('peliculas')->insert([
        [
            'titulo' => 'La bella y la bestia',
            'precio' => 7.00,
            'genero' => 'Fantasía',
            'directores' => 'Bill Condon',
            'edad_recomendada' => 'todos los públicos',
            'duracion' => '2h 3m',
            'fecha_estreno' => '2017/03/16',
            'sinopsis' => 'Una joven soñadora llamada Bella se ofrece a cambio de su padre como prisionera en el castillo de una misteriosa Bestia. Pronto descubre que el castillo está encantado y habitado por objetos que fueron humanos. A medida que conviven, Bella empieza a ver la humanidad oculta tras la apariencia monstruosa de la Bestia. El tiempo corre, y solo el amor verdadero puede romper el hechizo. Una historia de redención, magia y amor más allá de las apariencias.',
            'foto_grande' => '/images/films/1-labellaylabestia/fotogrande.webp',
            'actores' => 'Emma Watson, Dan Stevens, Luke Evans, Kevin Kline, Emma Thompson, Ewan McGregor, Josh Gad, Gugu Mbatha-Raw, Audra McDonald, Stanley Tucci, Adrian Schiller, Chris Andrew Mellow, Harriet Jones, Sonoya Mizuno',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=XpMjfUJ1lUc',
            'foto_miniatura' => '/images/films/1-labellaylabestia/miniatura.webp',
        ],
        [
            'titulo' => 'Forrest Gump',
            'precio' => 7.00,
            'genero' => 'Comedia-drama',
            'directores' => 'Robert Zemeckis',
            'edad_recomendada' => 'mayores de 13 años',
            'duracion' => '2h 22m',
            'fecha_estreno' => '1994/07/06',
            'sinopsis' => 'Forrest Gump, un hombre con un coeficiente intelectual bajo pero un corazón puro, narra su increíble vida marcada por momentos clave de la historia de EE.UU. Desde jugar fútbol americano hasta luchar en Vietnam o inspirar movimientos culturales, Forrest vive sin saber del todo su impacto. Mientras tanto, su amor por Jenny, su amiga de la infancia, permanece constante. Una historia conmovedora sobre inocencia, destino y resiliencia',
            'foto_grande' => '/images/films/2-forrestgump/fotogrande.webp',
            'actores' => 'Tom Hanks, Robin Wright, Gary Sinise, Mykelti Williamson',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=Cyh1LpxnaxI',
            'foto_miniatura' => '/images/films/2-forrestgump/fotominiatura.webp',
        ],
        [
            'titulo' => 'El Señor de Los Anillos: la Comunidad del Anillo',
            'precio' => 7.00,
            'genero' => 'Aventuras-fantasía Épica',
            'directores' => 'Peter Jackson',
            'edad_recomendada' => 'todos los públicos',
            'duracion' => '2h 58m',
            'fecha_estreno' => '2001/12/19',
            'sinopsis' => 'Frodo Bolsón, un joven hobbit, hereda un anillo que encierra un poder oscuro capaz de destruir el mundo. Guiado por el mago Gandalf, se une a una comunidad de héroes de distintas razas para emprender un peligroso viaje hacia Mordor, donde debe destruir el Anillo Único. A medida que avanzan, la unidad del grupo se ve amenazada por la corrupción del poder. Una épica aventura de amistad, valentía y lucha contra el mal.',
            'foto_grande' => '/images/films/3-elsenordelosanillos/fotogrande.webp',
            'actores' => 'Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mortensen, Sean Astin, Cate Blanchett',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=iFOucwxKRFE',
            'foto_miniatura' => '/images/films/3-elsenordelosanillos/fotominiatura.webp',
        ],
        [
            'titulo' => 'Titanic',
            'precio' => 7.00,
            'genero' => 'Romance, Catástrofe, Drama',
            'directores' => 'James Cameron',
            'edad_recomendada' => 'mayores de 12 años',
            'duracion' => '3h 15m',
            'fecha_estreno' => '1997/12/19',
            'sinopsis' => 'En el lujoso transatlántico Titanic, la joven aristócrata Rose conoce al artista pobre Jack durante su viaje inaugural. A pesar de sus diferencias sociales, nace entre ellos un amor profundo y rebelde. Pero su historia se ve truncada cuando el barco choca con un iceberg y comienza a hundirse. En medio del desastre, el amor y el sacrificio emergen como protagonistas. Una historia épica basada en la tragedia real de 1912.',
            'foto_grande' => '/images/films/4-titanic/fotogrande.webp',
            'actores' => 'Leonardo DiCaprio, Kate Winslet, Billy Zane, Gloria Stuart, Bill Paxton, Kathy Bates, Frances Fisher',
            'enlace_trailer' => 'https://www.youtube.com/embed/wMZuro21wtE?si=BoVm5UJ5TKDkRJYv',
            'foto_miniatura' => '/images/films/4-titanic/fotominiatura.webp',
        ],
        [
            'titulo' => 'Romper el Círculo',
            'precio' => 7.00,
            'genero' => 'Romance',
            'directores' => 'Justin Baldoni',
            'edad_recomendada' => 'mayores de 12 años',
            'duracion' => '2h 10m',
            'fecha_estreno' => '2024/08/09',
            'sinopsis' => 'Lily Bloom, una joven que tras superar una infancia marcada por la violencia, se muda a Boston para abrir su propia floristería. Allí conoce al carismático neurocirujano Ryle Kincaid, con quien inicia una intensa relación. Sin embargo, cuando su primer amor, Atlas Corrigan, reaparece, Lily se ve obligada a enfrentar su pasado y tomar decisiones difíciles para romper el ciclo de abuso que ha afectado su vida.',
            'foto_grande' => '/images/films/5-romperelcirculo/fotogrande.webp',
            'actores' => 'Blake Lively, Justin Baldoni, Jenny Slate, Hasan Minhaj, Brandon Sklenar',
            'enlace_trailer' => 'https://www.youtube.com/embed/aT_IzP2eJaU?si=SMEsM8fl_AdgDZQk',
            'foto_miniatura' => '/images/films/5-romperelcirculo/fotominiatura.webp',
        ],
        [
            'titulo' => 'El 47',
            'precio' => 7.00,
            'genero' => 'Drama Biográfico',
            'directores' => 'Marcel Barrena y Mònica Farrés',
            'edad_recomendada' => 'mayores de 7 años',
            'duracion' => '1h 50m',
            'fecha_estreno' => '2024/09/06',
            'sinopsis' => 'Óscar Camps, fundador de la ONG Proactiva Open Arms. La película sigue su transformación de socorrista de playa a activista humanitario tras presenciar la crisis de refugiados en el Mediterráneo. Con solo una lancha y determinación, desafía gobiernos y leyes para salvar vidas en altamar. Un retrato conmovedor de valentía, compromiso y solidaridad.',
            'foto_grande' => '/images/films/6-el47/fotogrande.webp',
            'actores' => 'Eduard Fernández, Salva Reina, Carlos Cuevas, Zoe Arnao, Mireia Vilapuig',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=PctPdv7LiuE',
            'foto_miniatura' => '/images/films/6-el47/fotominiatura.webp',
        ],
       [
            'titulo' => 'La estrella azul',
            'precio' => 7.00,
            'genero' => 'Drama, Música, Biográfico',
            'directores' => 'Javier Macipe',
            'edad_recomendada' => 'mayores de 12 años',
            'duracion' => '2h 8m',
            'fecha_estreno' => '2024/02/23',
            'sinopsis' => 'Durante los años noventa, Mauricio Aznar, un famoso rockero español, recorre Latinoamérica buscando reencontrarse con su vocación. Allí conoce a Don Carlos, un anciano músico en horas bajas que, a pesar de ser autor de algunas de las canciones más famosas del folclore de su país, apenas consigue pagar sus facturas. Carlos acoge con generosidad al extraño visitante haciendo las veces de maestro musical. De su encuentro nace un extravagante dúo quijotesco, con todos los visos de ser un absoluto fracaso comercial.',
            'foto_grande' => '/images/films/7-laestrellaazul/fotogrande.webp',
            'actores' => 'Pepe Lorente, Cuti Carabajal, Bruna Cusí, Marc Rodríguez, Catalina Sopelana, Mariela Carabajal, Noelia Verenice Díaz',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=SKHB1SRmrdA',
            'foto_miniatura' => '/images/films/7-laestrellaazul/fotominiatura.webp',
        ],
        [
            'titulo' => 'Del Revés',
            'precio' => 7.00,
            'genero' => 'Animación, Comedia Dramática, Aventura',
            'directores' => 'Pete Docter',
            'edad_recomendada' => 'todos los públicos',
            'duracion' => '1h 34m',
            'fecha_estreno' => '2015/05/18',
            'sinopsis' => 'Del Revés 1, conocida en inglés como Inside Out, es una película de animación de Disney y Pixar que sigue la vida de Riley, una niña de 11 años, y sus emociones internas personificadas como Alegría, Tristeza, Ira, Miedo y Asco. La película explora cómo estas emociones influyen en las decisiones y experiencias de Riley, especialmente cuando su familia se muda a San Francisco y ella se enfrenta a una nueva vida y a los cambios emocionales que conlleva.',
            'foto_grande' => '/images/films/8-delreves/fotogrande.webp',
            'actores' => 'Amy Poehler, Phyllis Smith, Richard Kind, Bill Hader, Lewis Black, Mindy Kaling',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=ZOWV9F7LnIQ',
            'foto_miniatura' => '/images/films/8-delreves/fotominiatura.webp',
        ],
        [
            'titulo' => 'Avengers: Endgame',
            'precio' => 7.00,
            'genero' => 'Acción, Ciencia Ficción',
            'directores' => 'Anthony y Joe Russo',
            'edad_recomendada' => 'mayores de 13 años',
            'duracion' => '3h 1m',
            'fecha_estreno' => '2019/04/26',
            'sinopsis' => 'Tras el devastador chasquido de Thanos, los Vengadores restantes se reúnen para revertir la tragedia y traer de vuelta a sus seres queridos. Con viajes en el tiempo y sacrificios profundos, el equipo lucha por una última oportunidad. La batalla final determinará el destino del universo.
                           "Avengers: Endgame" cierra una era épica del Universo Cinematográfico de Marvel con emoción, acción y despedidas inolvidables.',
            'foto_grande' => '/images/films/9-endgame/fotogrande.webp',
            'actores' => 'Robert Downey Jr., Chris Evans, Scarlett Johansson',
            'enlace_trailer' => 'https://www.youtube.com/embed/TcMBFSGVi1c',
            'foto_miniatura' => '/images/films/9-endgame/fotominiatura.webp',
        ],
        [
            'titulo' => 'Avatar',
            'precio' => 7.00,
            'genero' => 'Ciencia Ficción, Aventura',
            'directores' => 'James Cameron',
            'edad_recomendada' => 'mayores de 12 años',
            'duracion' => '2h 42m',
            'fecha_estreno' => '2009/12/18',
            'sinopsis' => 'En el año 2154, el exmarine Jake Sully viaja al exuberante planeta Pandora, donde los humanos explotan un mineral valioso. A través de un avatar, Jake se infiltra entre los Na’vi, los nativos del planeta. Mientras conoce su cultura y se enamora de Neytiri, empieza a cuestionar sus lealtades. El conflicto estalla entre la codicia humana y la defensa de la naturaleza. Jake deberá elegir de qué lado está en la lucha por Pandora.',
            'foto_grande' => '/images/films/10-avatar/fotogrande.webp',
            'actores' => 'Sam Worthington, Zoe Saldana, Sigourney Weaver',
            'enlace_trailer' => 'https://www.youtube.com/embed/5PSNL1qE6VY',
            'foto_miniatura' => '/images/films/10-avatar/fotominiatura.webp',
        ],
        [
            'titulo' => 'Spider-man: No Way Home',
            'precio' => 7.00,
            'genero' => 'Acción, Aventura, Superhéroes',
            'directores' => 'Jon Watts',
            'edad_recomendada' => 'mayores de 12 años',
            'duracion' => '2h 28m',
            'fecha_estreno' => '2021/12/17',
            'sinopsis' => 'Tras la revelación de su identidad secreta, la vida de Peter Parker se vuelve un caos. Desesperado, recurre al Doctor Strange para hacer que el mundo olvide que él es Spider-Man. Pero el hechizo sale mal y abre el multiverso, trayendo villanos de otras realidades. Para restaurar el equilibrio, Peter enfrentará desafíos que pondrán a prueba su madurez y sacrificio. Su lucha redefinirá lo que significa ser un héroe.',
            'foto_grande' => '/images/films/11-nowayhome/fotogrande.webp',
            'actores' => 'Tom Holland, Zendaya, Benedict Cumberbatch',
            'enlace_trailer' => 'https://www.youtube.com/embed/JfVOs4VSpmA',
            'foto_miniatura' => '/images/films/11-nowayhome/fotominiatura.webp',
        ],
        [
            'titulo' => 'Star Wars: El Despertar de la Fuerza',
            'precio' => 7.00,
            'genero' => 'Ciencia Ficción, Aventura',
            'directores' => 'J.J. Abrams',
            'edad_recomendada' => 'todos los públicos',
            'duracion' => '2h 18m',
            'fecha_estreno' => '2015/12/18',
            'sinopsis' => 'Treinta años después de la caída del Imperio, surge una nueva amenaza: la Primera Orden. Una chatarrera llamada Rey se ve envuelta en la lucha galáctica al encontrar al droide BB-8, que guarda un mapa hacia el desaparecido Luke Skywalker. Junto a Finn, Han Solo y Leia, Rey descubre su conexión con la Fuerza. Mientras el oscuro Kylo Ren busca imponer el caos, una nueva esperanza comienza a surgir.',
            'foto_grande' => '/images/films/12-eldespertardelafuerza/fotogrande.webp',
            'actores' => 'Daisy Ridley, John Boyega, Harrison Ford',
            'enlace_trailer' => 'https://www.youtube.com/embed/sGbxmsDFVnE',
            'foto_miniatura' => '/images/films/12-eldespertardelafuerza/fotominiatura.webp',
        ],
        [
            'titulo' => 'El Padrino',
            'precio' => 7.00,
            'genero' => 'Crimen, Drama',
            'directores' => 'Francis Ford Coppola',
            'edad_recomendada' => 'mayores de 18 años',
            'duracion' => '2h 55m',
            'fecha_estreno' => '1972/03/24',
            'sinopsis' => 'Don Vito Corleone, jefe de una influyente familia mafiosa, maneja su imperio con astucia y respeto. Tras un intento de asesinato, su hijo Michael se ve obligado a tomar el control. Al principio ajeno al crimen, Michael se transforma en un líder implacable. La historia narra el ascenso de un heredero inesperado en el mundo del poder y la traición. Un drama sobre familia, honor y corrupción en la América de la posguerra.',
            'foto_grande' => '/images/films/13-elpadrino/fotogrande.webp',
            'actores' => 'Marlon Brando, Al Pacino, James Caan',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=v72XprPxy3E',
            'foto_miniatura' => '/images/films/13-elpadrino/fotominiatura.webp',
        ],
        [
            'titulo' => 'Jurassic World',
            'precio' => 7.00,
            'genero' => 'Ciencia Ficción, Aventura',
            'directores' => 'Colin Trevorrow',
            'edad_recomendada' => 'mayores de 12 años',
            'duracion' => '2h 4m',
            'fecha_estreno' => '2015/06/12',
            'sinopsis' => 'Jurassic World, un parque temático con dinosaurios clonados, opera con éxito en la Isla Nublar. Para atraer más visitantes, los científicos crean un nuevo dinosaurio híbrido: el Indominus Rex. Sin embargo, la criatura escapa y desata el caos en el parque. Owen Grady, un entrenador de raptores, y Claire Dearing intentan salvar a los visitantes. La lucha por la supervivencia revela los peligros de jugar con la naturaleza.',
            'foto_grande' => '/images/films/14-jurassicworld/fotogrande.webp',
            'actores' => 'Chris Pratt, Bryce Dallas Howard',
            'enlace_trailer' => 'https://www.youtube.com/embed/RFinNxS5KN4',
            'foto_miniatura' => '/images/films/14-jurassicworld/fotominiatura.webp',
        ],
        [
            'titulo' => 'El Rey León',
            'precio' => 7.00,
            'genero' => 'Animación, Aventura, Drama',
            'directores' => 'Jon Favreau',
            'edad_recomendada' => 'todos los públicos',
            'duracion' => '1h 58m',
            'fecha_estreno' => '2019/07/19',
            'sinopsis' => 'Simba, un joven león heredero al trono, huye tras la trágica muerte de su padre, el rey Mufasa. En el exilio, crece y aprende valiosas lecciones sobre la vida y la responsabilidad. Con la ayuda de nuevos y viejos amigos, deberá enfrentar su pasado. Simba regresa a las Tierras del Reino para reclamar su lugar como rey.',
            'foto_grande' => '/images/films/15-lionking/fotogrande.webp',
            'actores' => 'Donald Glover, Beyoncé, James Earl Jones',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=mb79ctR-E-c',
            'foto_miniatura' => '/images/films/15-lionking/fotominiatura.webp',
        ],
        [
            'titulo' => 'Frozen II',
            'precio' => 7.00,
            'genero' => 'Animación, Aventura, Musical',
            'directores' => 'Chris Buck, Jennifer Lee',
            'edad_recomendada' => 'todos los públicos',
            'duracion' => '1h 43m',
            'fecha_estreno' => '2019/11/22',
            'sinopsis' => 'Elsa comienza a escuchar una misteriosa voz que la llama desde el norte. Junto a Anna, Kristoff, Olaf y Sven, emprende un viaje para descubrir el origen de sus poderes. En el bosque encantado, enfrentan secretos del pasado que podrían cambiar su reino para siempre. Elsa deberá encontrar la verdad para salvar Arendelle. La aventura revela que el poder más fuerte es el de la verdad y la unión familiar.',
            'foto_grande' => '/images/films/16-frozenII/fotogrande.webp',
            'actores' => 'Idina Menzel, Kristen Bell, Josh Gad',
            'enlace_trailer' => 'https://www.youtube.com/embed/Zi4LMpSDccc',
            'foto_miniatura' => '/images/films/16-frozenII/fotominiatura.webp',
        ],
        [
            'titulo' => 'Fast and Furious 7',
            'precio' => 7.00,
            'genero' => 'Acción, Thriller',
            'directores' => 'James Wan',
            'edad_recomendada' => 'mayores de 13 años',
            'duracion' => '2h 17m',
            'fecha_estreno' => '2015/04/03',
            'sinopsis' => 'Después de derrotar a Owen Shaw, Dominic Toretto y su equipo enfrentan una nueva amenaza: Deckard Shaw, el hermano mayor que busca venganza. Mientras intentan protegerse, son reclutados por una agencia gubernamental para recuperar un poderoso dispositivo. Las carreras y la acción se intensifican por todo el mundo. La familia vuelve a ser el motor de la historia. La película también rinde homenaje al fallecido Paul Walker.',
            'foto_grande' => '/images/films/17-fastandfurious/fotogrande.webp',
            'actores' => 'Vin Diesel, Paul Walker, Jason Statham',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=tX0MGnC41nk',
            'foto_miniatura' => '/images/films/17-fastandfurious/fotominiatura.webp',
        ],
        [
            'titulo' => 'Harry Potter y la Piedra Filosofal',
            'precio' => 7.00,
            'genero' => 'Fantasía',
            'directores' => 'Chris Columbus',
            'edad_recomendada' => 'todos los públicos',
            'duracion' => '2h 32m',
            'fecha_estreno' => '2001/11/16',
            'sinopsis' => 'El día en que cumple once años, Harry Potter descubre que es hijo de dos conocidos hechiceros, de los que ha heredado poderes mágicos. Deberá acudir entonces a una famosa escuela de magia y hechicería: Howards.',
            'foto_grande' => '/images/films/18-harrypotter/fotogrande.webp',
            'actores' => 'Daniel Radcliffe, Rupert Grint, Emma Watson, John Cleese, Robbie Coltrane, Warwick Davis, Richard Griffiths, Richard Harris, Ian Hart',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=WE4AJuIvG1Y',
            'foto_miniatura' => '/images/films/18-harrypotter/fotominiatura.webp',
        ],
        [
            'titulo' => 'Wall-E',
            'precio' => 7.00,
            'genero' => 'Animación, Ciencia ficción, Comedia, Romance',
            'directores' => 'Andrew Stanton',
            'edad_recomendada' => 'todos los públicos',
            'duracion' => '1h 38m',
            'fecha_estreno' => '2008/06/27',
            'sinopsis' => 'En el año 2805, la Tierra está deshabitada y cubierta de basura. WALL·E, un pequeño robot recolector de residuos, lleva siglos limpiando el planeta en soledad. Su rutina cambia cuando llega EVE, una robot enviada para buscar signos de vida. Juntos emprenden una aventura que podría determinar el futuro de la humanidad.',
            'foto_grande' => '/images/films/19-walle/fotogrande.webp',
            'actores' => 'Ben Burtt, Elissa Knight, Jeff Garlin, Fred Willard, Sigourney Weaver',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=qF7p4lZ00RA',
            'foto_miniatura' => '/images/films/19-walle/fotominiatura.webp',
        ],
        [
            'titulo' => 'La Vida es Bella',
            'precio' => 7.00,
            'genero' => 'Drama, Comedia, Romance, Bélico',
            'directores' => 'Roberto Benigni',
            'edad_recomendada' => 'mayores de 13 años',
            'duracion' => '1h 56m',
            'fecha_estreno' => '1997/12/20',
            'sinopsis' => 'Guido, un hombre judío italiano, utiliza su imaginación y humor para proteger a su hijo de los horrores del Holocausto cuando ambos son enviados a un campo de concentración nazi.',
            'foto_grande' => '/images/films/20-lavidaesbella/fotogrande.webp',
            'actores' => 'Roberto Benigni, Nicoletta Braschi, Giorgio Cantarini',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=e-Z062tRdbQ',
            'foto_miniatura' => '/images/films/20-lavidaesbella/fotominiatura.webp',
        ],
        [
            'titulo' => 'El club de la Lucha',
            'precio' => 7.00,
            'genero' => 'Drama, Thriller',
            'directores' => 'David Fincher',
            'edad_recomendada' => 'mayores de 16 años',
            'duracion' => '2h 19m',
            'fecha_estreno' => '1999/10/15',
            'sinopsis' => 'Un hombre insomne y desencantado de la vida conoce a un carismático vendedor de jabón, Tyler Durden. Juntos forman un club clandestino donde hombres pueden liberar su furia mediante peleas físicas. A medida que el club evoluciona, toma un rumbo violento y anarquista. El narrador comienza a perder el control sobre su propia realidad. Pronto descubre una verdad perturbadora que cambiará todo.',
            'foto_grande' => '/images/films/21-elclubdelalucha/fotogrande.webp',
            'actores' => 'Brad Pitt, Edward Norton, Helena Bonham Carter',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=r5KDiUNZv4w',
            'foto_miniatura' => '/images/films/21-elclubdelalucha/fotominiatura.webp',
        ],
        [
            'titulo' => 'Psicosis',
            'precio' => 7.00,
            'genero' => 'Terror, Thriller, Misterio',
            'directores' => 'Alfred Hitchcock',
            'edad_recomendada' => 'mayores de 16 años',
            'duracion' => '1h 49m',
            'fecha_estreno' => '1960/06/16',
            'sinopsis' => 'Marion Crane roba dinero y huye, encontrando refugio en un motel apartado regentado por el tímido Norman Bates. Lo que parece un lugar seguro pronto se convierte en una pesadilla.',
            'foto_grande' => '/images/films/22-psicosis/fotogrande.webp',
            'actores' => 'Anthony Perkins, Janet Leigh, Vera Miles, John Gavin',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=mC2gOyWuSEY',
            'foto_miniatura' => '/images/films/22-psicosis/fotominiatura.webp',
        ],
        [
            'titulo' => 'Parásitos',
            'precio' => 7.00,
            'genero' => 'Thriller, drama',
            'directores' => 'Bong Joon-ho',
            'edad_recomendada' => 'mayores de 16 años',
            'duracion' => '2h 12m',
            'fecha_estreno' => '2019/05/30',
            'sinopsis' => 'La familia Kim, que vive en la pobreza, se infiltra poco a poco en la vida de los ricos Park al conseguir empleos en su casa sin revelar su relación entre ellos. A medida que se entrelazan ambas familias, surgen tensiones ocultas y secretos oscuros. Lo que comienza como una farsa cómica se transforma en una crítica social intensa. El contraste entre clases sociales estalla con consecuencias inesperadas. Una historia mordaz sobre desigualdad y supervivencia.',
            'foto_grande' => '/images/films/23-parasitos/fotogrande.webp',
            'actores' => 'Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=90dWVETAdtI',
            'foto_miniatura' => '/images/films/23-parasitos/fotominiatura.webp',
        ],
        [
            'titulo' => 'El Diario de Noa',
            'precio' => 7.00,
            'genero' => 'Romance, Drama',
            'directores' => 'Nick Cassavetes',
            'edad_recomendada' => 'mayores de 13 años',
            'duracion' => '2h 3m',
            'fecha_estreno' => '2004/06/25',
            'sinopsis' => 'En una residencia de ancianos, un hombre lee a una mujer la historia de dos jóvenes enamorados. Noah y Allie provienen de mundos diferentes, pero viven un amor intenso durante un verano inolvidable. La vida y las circunstancias los separan, pero el destino los vuelve a cruzar. A través del relato, se revela un poderoso vínculo que desafía el tiempo y la memoria. Es una historia sobre el amor verdadero y su permanencia.',
            'foto_grande' => '/images/films/24-eldiariodenoa/fotogrande.webp',
            'actores' => 'Ryan Gosling, Rachel Mcadams, James Garner, Gena Rowlands',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=fwlmQ3PCZ9g',
            'foto_miniatura' => '/images/films/24-eldiariodenoa/fotominiatura.webp',
        ],
        [
            'titulo' => 'Elegir Un Amor',
            'precio' => 7.00,
            'genero' => 'Romance, Drama',
            'directores' => 'Stuart Hazeldine',
            'edad_recomendada' => 'mayores de 13 años',
            'duracion' => '1h 49m',
            'fecha_estreno' => '2023/09/15',
            'sinopsis' => 'Emma, una joven escritora en busca de inspiración, se enfrenta a una difícil decisión cuando debe elegir entre su amor de la infancia y un carismático desconocido. Cada uno representa un camino distinto en su vida. Mientras explora sus emociones, descubre verdades profundas sobre sí misma. Su elección no solo definirá su futuro amoroso, sino también su identidad.',
            'foto_grande' => '/images/films/25-elegirunamor/fotogrande.webp',
            'actores' => 'Laura Marano, Avan Jogia, Scott Michael Foster',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=A8p0w_Ec1NY',
            'foto_miniatura' => '/images/films/25-elegirunamor/fotominiatura.webp',
        ],
        [
            'titulo' => 'Vaiana',
            'precio' => 7.00,
            'genero' => 'Animación, Aventura, Musical, Fantasía',
            'directores' => 'John Musker y Ron Clements',
            'edad_recomendada' => 'todos los públicos',
            'duracion' => '1h 47m',
            'fecha_estreno' => '2016/11/23',
            'sinopsis' => 'Vaiana, una valiente joven polinesia, es elegida por el océano para devolver el corazón robado de Te Fiti y salvar su isla. Emprende un viaje épico junto al semidiós Maui, enfrentando criaturas míticas y desafíos en alta mar. A lo largo del camino, descubre su verdadera identidad y fuerza interior. Su determinación cambiará el destino de su pueblo.',
            'foto_grande' => '/images/films/26-vaiana/fotogrande.webp',
            'actores' => 'Auli\'i Cravalho, Dwayne Johnson, Rachel House, Temuera Morrison, Nicole Scherzinger, Jemaine Clement, Alan Tudyk',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=tmpTGztGJ8E',
            'foto_miniatura' => '/images/films/26-vaiana/fotominiatura.webp',
        ],
        [
            'titulo' => 'Coco',
            'precio' => 7.00,
            'genero' => 'Animación, aventura, familiar',
            'directores' => 'Lee Unkrich, Adrian Molina',
            'edad_recomendada' => 'todos los públicos',
            'duracion' => '1h 45m',
            'fecha_estreno' => '2017/11/22',
            'sinopsis' => 'Miguel, un niño que sueña con ser músico, se adentra accidentalmente en la Tierra de los Muertos durante el Día de los Muertos. Allí busca a su tatarabuelo, un famoso músico, para obtener su bendición y poder volver al mundo de los vivos. En su viaje, descubre secretos sobre su familia y el verdadero valor de la memoria. A través de la música y el amor familiar, Miguel cambiará su destino.',
            'foto_grande' => '/images/films/27-coco/fotogrande.webp',
            'actores' => 'Anthony Gonzalez, Gael García Bernal, Benjamin Bratt',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=R7wo-0Q0u4g',
            'foto_miniatura' => '/images/films/27-coco/fotominiatura.webp',
        ],
        [
            'titulo' => 'Marcelino, Pan y Vino',
            'precio' => 7.00,
            'genero' => 'Drama religioso',
            'directores' => 'Ladislao Vajda',
            'edad_recomendada' => 'todos los públicos',
            'duracion' => '1h 31min',
            'fecha_estreno' => '1955/02/24',
            'sinopsis' => 'Marcelino es un niño huérfano criado por frailes en un convento. Un día descubre una figura de Cristo en el desván y, movido por la compasión, le ofrece pan y vino. Milagrosamente, la figura cobra vida y le concede su mayor deseo: conocer a su madre.',
            'foto_grande' => '/images/films/28-marcelinopanyvino/fotogrande.webp',
            'actores' => 'Pablito Calvo, Rafael Rivelles, Antonio Vico, Juan Calvo, José Marco Davó, José Nieto, Fernando Rey, Juanjo Menéndez, Jesús Tordesillas, María Isbert, Manuel Alexandre',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=bN4fvv-G5vE',
            'foto_miniatura' => '/images/films/28-marcelinopanyvino/fotominiatura.webp',
        ],
        [
            'titulo' => 'Gladiator',
            'precio' => 7.00,
            'genero' => 'Acción, drama, historia',
            'directores' => 'Ridley Scott',
            'edad_recomendada' => 'mayores de 16 años',
            'duracion' => '2h 35m',
            'fecha_estreno' => '2000/05/05',
            'sinopsis' => 'Máximo Décimo Meridio, un leal general romano, es traicionado cuando el corrupto hijo del emperador asesina a su familia y lo condena a la esclavitud. Convertido en gladiador, lucha por sobrevivir en la arena mientras gana fama y apoyo. Su objetivo final es vengar a su familia y restaurar el honor de Roma. En su camino, desafiará al Imperio desde el corazón del Coliseo.',
            'foto_grande' => '/images/films/29-gladiator/fotogrande.webp',
            'actores' => 'Russell Crowe, Joaquin Phoenix',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=Pb6WME02hdA',
            'foto_miniatura' => '/images/films/29-gladiator/fotominiatura.webp',
        ],
        [
            'titulo' => 'Capitán América 1',
            'precio' => 7.00,
            'genero' => 'Acción, Aventura, Ciencia ficción, Superhéroes',
            'directores' => 'Joe Johnston',
            'edad_recomendada' => 'mayores de 7 años',
            'duracion' => '2h 4m',
            'fecha_estreno' => '2011/07/22',
            'sinopsis' => 'Durante la Segunda Guerra Mundial, Steve Rogers, un joven con problemas de salud, se ofrece como voluntario para un experimento que lo transforma en el supersoldado Capitán América. Armado con su escudo y su valentía, lucha contra la organización HYDRA liderada por el malvado Cráneo Rojo.',
            'foto_grande' => '/images/films/30-capitanamerica1/fotogrande.webp',
            'actores' => 'Chris Evans, Hayley Atwell, Sebastian Stan, Tommy Lee Jones',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=YqEJ0jpFvSU',
            'foto_miniatura' => '/images/films/30-capitanamerica1/fotominiatura.webp',
        ],
        [
            'titulo' => 'La momia regresa',
            'precio' => 7.00,
            'genero' => 'Acción, Aventura, Fantasía',
            'directores' => 'Stephen Sommers',
            'edad_recomendada' => 'mayores de 13 años',
            'duracion' => '2h 9m',
            'fecha_estreno' => '2001/05/04',
            'sinopsis' => 'Diez años después de los eventos de la primera película, Rick y Evelyn O\'Connell viven en Londres con su hijo Alex. La familia se ve envuelta en una nueva aventura cuando el brazalete de Anubis despierta al Rey Escorpión, una antigua amenaza que podría destruir el mundo. Para detenerlo, deberán enfrentarse nuevamente a Imhotep, resucitado por una secta que busca controlar el ejército del Rey Escorpión.',
            'foto_grande' => '/images/films/31-lamomia/fotogrande.webp',
            'actores' => 'Brendan Fraser, Rachel Weisz, John Hannah, Arnold Vosloo, Oded Fehr, Patricia Velásquez, Freddie Boath, Dwayne Johnson',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=c67PSYSbzMY',
            'foto_miniatura' => '/images/films/31-lamomia/fotominiatura.webp',
        ],
        [
            'titulo' => 'La lista de Schindler',
            'precio' => 7.00,
            'genero' => 'Drama, Historia, Bélico',
            'directores' => 'Steven Spielberg',
            'edad_recomendada' => 'mayores de 16 años',
            'duracion' => '3h 15m',
            'fecha_estreno' => '1993/12/15',
            'sinopsis' => 'Durante la Segunda Guerra Mundial, el empresario alemán Oskar Schindler salva a más de mil judíos polacos del Holocausto al emplearlos en sus fábricas. Lo que comienza como un interés económico se transforma en una lucha humanitaria cuando Schindler se enfrenta a la brutal realidad del régimen nazi.',
            'foto_grande' => '/images/films/32-schindler/fotogrande.webp',
            'actores' => 'Liam Neeson, Ben Kingsley, Ralph Fiennes, Caroline Goodall, Embeth Davidtz',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=BmkchuRJ82w',
            'foto_miniatura' => '/images/films/32-schindler/fotominiatura.webp',
        ],
        [
            'titulo' => 'Lágrimas del sol',
            'precio' => 7.00,
            'genero' => 'Acción, Drama, Bélico',
            'directores' => 'Antoine Fuqua',
            'edad_recomendada' => 'mayores de 16 años',
            'duracion' => '2h',
            'fecha_estreno' => '2003/03/07',
            'sinopsis' => 'Un equipo de Navy SEALs liderado por el teniente A.K. Waters es enviado a Nigeria para rescatar a la doctora Lena Kendricks, una ciudadana estadounidense atrapada en medio de una guerra civil. Lo que comienza como una misión rápida se convierte en una lucha moral cuando Waters debe decidir entre seguir órdenes o proteger a un grupo de refugiados inocentes.',
            'foto_grande' => '/images/films/33-lagrimasdelsol/fotogrande.webp',
            'actores' => 'Bruce Willis, Monica Bellucci, Cole Hauser, Eamonn Walker, Johnny Messner, Fionnula Flanagan, Tom Skerritt',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=EiaMa-IdXCc',
            'foto_miniatura' => '/images/films/33-lagrimasdelsol/fotominiatura.webp',
        ],
        [
            'titulo' => 'Sin instrucciones',
            'precio' => 6.50,
            'genero' => 'Drama, Comedia',
            'directores' => 'Eugenio Derbez',
            'edad_recomendada' => 'mayores de 13 años',
            'duracion' => '1h 55m',
            'fecha_estreno' => '2013/09/20',
            'sinopsis' => 'Valentín, un mujeriego de Acapulco, ve su vida cambiar cuando una exnovia le deja una bebé en la puerta de su casa. Decide ir a Los Ángeles a buscar a la madre, pero termina criando a la niña durante años, convirtiéndose en un padre amoroso. Cuando la madre reaparece, Valentín deberá luchar por conservar la custodia de su hija adoptiva.',
            'foto_grande' => '/images/films/34-sininstrucciones/fotogrande.webp',
            'actores' => 'Eugenio Derbez, Loreto Peralta, Jessica Lindsey, Daniel Raymont, Alessandra Rosaldo',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=YtXjZ2U1oTo',
            'foto_miniatura' => '/images/films/34-sininstrucciones/fotominiatura.webp',
        ],
        [
            'titulo' => 'Palmeras en la nieve',
            'precio' => 7.00,
            'genero' => 'Drama, Romance',
            'directores' => 'Fernando González Molina',
            'edad_recomendada' => 'mayores de 16 años',
            'duracion' => '2h 43m',
            'fecha_estreno' => '2015/12/25',
            'sinopsis' => 'En 1953, Kilian abandona la nieve de las montañas oscenses para emprender junto a su hermano un viaje a una tierra exótica y lejana, la isla de Fernando Poo, una colonia española en Guinea Ecuatorial. Allí descubrirá el amor y los secretos que marcarán a su familia durante generaciones.',
            'foto_grande' => '/images/films/35-palmeras/fotogrande.webp',
            'actores' => 'Mario Casas, Adriana Ugarte, Macarena García, Berta Vázquez, Emilio Gutiérrez Caba',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=3S6Fh2T1v5g',
            'foto_miniatura' => '/images/films/35-palmeras/fotominiatura.webp',
        ],
        [
            'titulo' => 'Demon Slayer: Mugen Train',
            'precio' => 7.00,
            'genero' => 'Animación, Acción, Fantasía',
            'directores' => 'Haruo Sotozaki',
            'edad_recomendada' => 'mayores de 13 años',
            'duracion' => '1h 57m',
            'fecha_estreno' => '2021/04/23',
            'sinopsis' => 'Tanjiro y sus compañeros del Cuerpo de Cazadores de Demonios se embarcan en una nueva misión a bordo del Tren Infinito. Más de 40 personas han desaparecido misteriosamente, y ellos deben enfrentarse a un poderoso demonio que los arrastrará a una pesadilla onírica.',
            'foto_grande' => '/images/films/36-demonslayer/fotogrande.webp',
            'actores' => 'Natsuki Hanae, Akari Kitō, Hiro Shimono, Yoshitsugu Matsuoka, Satoshi Hino',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=ATJYac_dORw',
            'foto_miniatura' => '/images/films/36-demonslayer/fotominiatura.webp',
        ],
        [
            'titulo' => 'La familia Addams',
            'precio' => 7.00,
            'genero' => 'Animación, Comedia, Familia',
            'directores' => 'Greg Tiernan, Conrad Vernon',
            'edad_recomendada' => 'mayores de 7 años',
            'duracion' => '1h 27m',
            'fecha_estreno' => '2019/10/25',
            'sinopsis' => 'La macabra y divertida familia Addams se enfrenta a una nueva amenaza cuando se mudan a una ciudad suburbana, donde su estilo de vida oscuro y excéntrico choca con la perfección del vecindario.',
            'foto_grande' => '/images/films/37-lafamilia/fotogrande.webp',
            'actores' => 'Oscar Isaac, Charlize Theron, Chloë Grace Moretz, Finn Wolfhard, Nick Kroll',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=O-1jv4dx4IY',
            'foto_miniatura' => '/images/films/37-lafamilia/fotominiatura.webp',
        ],
        [
            'titulo' => 'Ghost',
            'precio' => 7.00,
            'genero' => 'Drama, Romance, Fantasía',
            'directores' => 'Jerry Zucker',
            'edad_recomendada' => 'mayores de 13 años',
            'duracion' => '2h 7m',
            'fecha_estreno' => '1990/07/13',
            'sinopsis' => 'Sam es asesinado en un aparente robo, pero su espíritu permanece en el mundo de los vivos para proteger a su amada Molly del verdadero peligro. Con la ayuda de una médium excéntrica, intentará comunicarse con ella y advertirle lo que realmente está ocurriendo.',
            'foto_grande' => '/images/films/38-ghost/fotogrande.webp',
            'actores' => 'Patrick Swayze, Demi Moore, Whoopi Goldberg, Tony Goldwyn, Rick Aviles',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=6CRc7IMjW2g',
            'foto_miniatura' => '/images/films/38-ghost/fotominiatura.webp',
        ],
        [
            'titulo' => 'El niño con el pijama de rayas',
            'precio' => 7.00,
            'genero' => 'Drama, Bélica',
            'directores' => 'Mark Herman',
            'edad_recomendada' => 'mayores de 13 años',
            'duracion' => '1h 34m',
            'fecha_estreno' => '2008/09/12',
            'sinopsis' => 'Durante la Segunda Guerra Mundial, Bruno, un niño alemán de ocho años, se muda con su familia cerca de un campo de concentración. Allí conoce a Shmuel, un niño judío con el que entabla una amistad prohibida a través de una valla, sin comprender del todo la trágica realidad que los rodea.',
            'foto_grande' => '/images/films/39-elniño/fotogrande.webp',
            'actores' => 'Asa Butterfield, Jack Scanlon, Vera Farmiga, David Thewlis, Amber Beattie',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=zV8v5H4FZ3g',
            'foto_miniatura' => '/images/films/39-elniño/fotominiatura.webp',
        ],
        [
            'titulo' => 'El Conjuro',
            'precio' => 7.00,
            'genero' => 'Terror, Suspenso',
            'directores' => 'James Wan',
            'edad_recomendada' => 'mayores de 16 años',
            'duracion' => '1h 52m',
            'fecha_estreno' => '2013/07/19',
            'sinopsis' => 'Basada en hechos reales, la historia sigue a Ed y Lorraine Warren, investigadores de fenómenos paranormales, que ayudan a una familia aterrorizada por una presencia oscura en su granja. A medida que investigan, descubren un pasado aterrador ligado a la casa.',
            'foto_grande' => '/images/films/40-elconjuro/fotogrande.webp',
            'actores' => 'Vera Farmiga, Patrick Wilson, Lili Taylor, Ron Livingston, Joey King',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=k10ETZ41q5o',
            'foto_miniatura' => '/images/films/40-elconjuro/fotominiatura.webp',
        ],
        [
            'titulo' => 'Paranormal Activity 2',
            'precio' => 7.00,
            'genero' => 'Terror, Suspenso',
            'directores' => 'Tod Williams',
            'edad_recomendada' => 'mayores de 16 años',
            'duracion' => '1h 31m',
            'fecha_estreno' => '2010/10/22',
            'sinopsis' => 'Después de experimentar una aparente invasión a su hogar, una familia instala cámaras de seguridad, sin imaginar que captarán una serie de sucesos paranormales cada vez más intensos. La historia se conecta con los eventos de la primera película, revelando el origen del mal.',
            'foto_grande' => '/images/films/41-paranormal/fotogrande.webp',
            'actores' => 'Sprague Grayden, Brian Boland, Molly Ephraim, Katie Featherston, Micah Sloat',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=07XbSkY7f2Y',
            'foto_miniatura' => '/images/films/41-paranormal/fotominiatura.webp',
        ],
        [
            'titulo' => 'Mamá',
            'precio' => 7.00,
            'genero' => 'Terror, Suspenso, Fantasía',
            'directores' => 'Andrés Muschietti',
            'edad_recomendada' => 'mayores de 16 años',
            'duracion' => '1h 40m',
            'fecha_estreno' => '2013/01/18',
            'sinopsis' => 'Dos niñas desaparecen en el bosque tras la muerte de sus padres. Años después, son encontradas y acogidas por su tío y su novia. Sin embargo, una presencia oscura a la que llaman "Mamá" las ha acompañado todo ese tiempo... y no está dispuesta a dejarlas ir.',
            'foto_grande' => '/images/films/42-mama/fotogrande.webp',
            'actores' => 'Jessica Chastain, Nikolaj Coster-Waldau, Megan Charpentier, Isabelle Nélisse, Daniel Kash',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=7Am7i7uM9r0',
            'foto_miniatura' => '/images/films/42-mama/fotominiatura.webp',
        ],
        [
            'titulo' => 'This Is It',
            'precio' => 7.00,
            'genero' => 'Documental, Música',
            'directores' => 'Kenny Ortega',
            'edad_recomendada' => 'mayores de 7 años',
            'duracion' => '1h 51m',
            'fecha_estreno' => '2009/10/28',
            'sinopsis' => 'Este documental ofrece una mirada íntima a los ensayos y preparativos del que iba a ser el último gran espectáculo de Michael Jackson. Con imágenes inéditas, entrevistas y números musicales, muestra la dedicación y genialidad del "Rey del Pop" en sus últimos días.',
            'foto_grande' => '/images/films/43-thisisit/fotogrande.webp',
            'actores' => 'Michael Jackson, Kenny Ortega, Alex Al, Orianthi, Tommy Organ',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=cyrkcz7msfY',
            'foto_miniatura' => '/images/films/43-thisisit/fotominiatura.webp',
        ],
        [
            'titulo' => 'Bowling for Columbine',
            'precio' => 7.00,
            'genero' => 'Documental',
            'directores' => 'Michael Moore',
            'edad_recomendada' => 'mayores de 13 años',
            'duracion' => '2h',
            'fecha_estreno' => '2002/10/11',
            'sinopsis' => 'Michael Moore investiga las causas de la violencia armada en Estados Unidos, con especial énfasis en la masacre de Columbine. Mezclando entrevistas, sátira y datos, ofrece una crítica al sistema político, mediático y cultural del país.',
            'foto_grande' => '/images/films/44-bowling/fotogrande.webp',
            'actores' => 'Michael Moore, Marilyn Manson, Charlton Heston',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=hH0mSAjp_Jw',
            'foto_miniatura' => '/images/films/44-bowling/fotominiatura.webp',
        ],
        [
            'titulo' => 'Sin perdón',
            'precio' => 7.00,
            'genero' => 'Western, Drama',
            'directores' => 'Clint Eastwood',
            'edad_recomendada' => 'mayores de 16 años',
            'duracion' => '2h 11m',
            'fecha_estreno' => '1992/08/07',
            'sinopsis' => 'William Munny, un antiguo pistolero retirado, acepta un último trabajo junto a su viejo compañero. Enfrentan la violencia, la ley corrupta y sus propios fantasmas en un crudo retrato del salvaje oeste.',
            'foto_grande' => '/images/films/45-sinperdon/fotogrande.webp',
            'actores' => 'Clint Eastwood, Gene Hackman, Morgan Freeman',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=ftTX4FoBWlE',
            'foto_miniatura' => '/images/films/45-sinperdon/fotominiatura.webp',
        ],
        [
            'titulo' => 'Chinatown',
            'precio' => 7.00,
            'genero' => 'Crimen, Misterio, Noir',
            'directores' => 'Roman Polanski',
            'edad_recomendada' => 'mayores de 16 años',
            'duracion' => '2h 10m',
            'fecha_estreno' => '1974/06/20',
            'sinopsis' => 'Jake Gittes, un detective privado, se ve envuelto en una compleja red de corrupción, traición y asesinato en el Los Ángeles de los años 30, mientras investiga un aparente caso de infidelidad.',
            'foto_grande' => '/images/films/46-chinatown/fotogrande.webp',
            'actores' => 'Jack Nicholson, Faye Dunaway, John Huston',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=beVX_JZ1CWY',
            'foto_miniatura' => '/images/films/46-chinatown/fotominiatura.webp',
        ],
        [
            'titulo' => 'Jojo Rabbit',
            'precio' => 7.00,
            'genero' => 'Comedia, Bélico, Satírica, Drama',
            'directores' => 'Taika Waititi',
            'edad_recomendada' => 'mayores de 13 años',
            'duracion' => '1h 48m',
            'fecha_estreno' => '2019/10/18',
            'sinopsis' => 'Jojo es un niño alemán cuya visión del mundo cambia cuando descubre que su madre esconde a una niña judía. Con la ayuda de su amigo imaginario: Adolf Hitler, deberá replantearse todo lo que creía.',
            'foto_grande' => '/images/films/47-jojo/fotogrande.webp',
            'actores' => 'Roman Griffin Davis, Scarlett Johansson, Taika Waititi',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=tL4McUzXfFI',
            'foto_miniatura' => '/images/films/47-jojo/fotominiatura.webp',
        ],
        [
            'titulo' => 'Lady Bird',
            'precio' => 7.00,
            'genero' => 'Drama, Coming-of-age',
            'directores' => 'Greta Gerwig',
            'edad_recomendada' => 'mayores de 13 años',
            'duracion' => '1h 34m',
            'fecha_estreno' => '2017/11/03',
            'sinopsis' => 'Christine "Lady Bird" McPherson, una adolescente rebelde, navega los altibajos del último año de secundaria, su relación con su madre y sus aspiraciones artísticas en Sacramento, California.',
            'foto_grande' => '/images/films/48-ladybird/fotogrande.webp',
            'actores' => 'Saoirse Ronan, Laurie Metcalf, Timothée Chalamet',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=cNi_HC839Wo',
            'foto_miniatura' => '/images/films/48-ladybird/fotominiatura.webp',
        ],
        [
            'titulo' => 'Los juegos del hambre',
            'precio' => 7.00,
            'genero' => 'Acción, Distopía, Ciencia ficción',
            'directores' => 'Gary Ross',
            'edad_recomendada' => 'mayores de 12 años',
            'duracion' => '2h 22m',
            'fecha_estreno' => '2012/03/23',
            'sinopsis' => 'En un futuro distópico, Katniss Everdeen se ofrece voluntaria para participar en los Juegos del Hambre, una competencia televisada donde 24 jóvenes deben luchar a muerte por la supervivencia.',
            'foto_grande' => '/images/films/49-juegosdelhambre/fotogrande.webp',
            'actores' => 'Jennifer Lawrence, Josh Hutcherson, Woody Harrelson',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=mfmrPu43DF8',
            'foto_miniatura' => '/images/films/49-juegosdelhambre/fotominiatura.webp',
        ],
        [
            'titulo' => 'El cisne negro',
            'precio' => 7.00,
            'genero' => 'Drama, Psicológico, Thriller',
            'directores' => 'Darren Aronofsky',
            'edad_recomendada' => 'mayores de 16 años',
            'duracion' => '1h 48m',
            'fecha_estreno' => '2010/12/03',
            'sinopsis' => 'Nina, una bailarina obsesionada con alcanzar la perfección, consigue el papel principal en "El lago de los cisnes". Pero la presión y la competencia la llevan a una espiral de paranoia y transformación.',
            'foto_grande' => '/images/films/50-elcisnenegro/fotogrande.webp',
            'actores' => 'Natalie Portman, Mila Kunis, Vincent Cassel',
            'enlace_trailer' => 'https://www.youtube.com/watch?v=5jaI1XOB-bs',
            'foto_miniatura' => '/images/films/50-elcisnenegro/fotominiatura.webp',
        ],
        ]);
    }
}
