version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8080:80"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=your-postgres-host.render.com
      - DB_PORT=5432
      - DB_DATABASE=yourdbname
      - DB_USERNAME=youruser
      - DB_PASSWORD=yourpassword
    networks:
      - laravel

networks:
  laravel:
